### ISSUE TITLE
Add support for Brocade FCX

### ISSUE THREAD

**Issue by bcix** [opensolutions/OSS_SNMP#12]
Hey,

and another Brocade devices which is not detected by IXP-Manager:

```snmpget -c <>  -On -v 2c brocade-fcx .1.3.6.1.2.1.1.1.0```
```
.1.3.6.1.2.1.1.1.0 = STRING: "Brocade Communications Systems, Inc. FCX624S, IronWare Version 08.0.10T7f1 Compiled on Jan 07 2014 at 09:13:59 labeled as FCXS08010"
```
```snmpget -c <>  -On -v 2c brocade-fcx .1.3.6.1.2.1.1.2.0```

```
.1.3.6.1.2.1.1.2.0 = OID: .1.3.6.1.4.1.1991.1.3.54.1.1.1.1
```

And the serial number:

```snmpget -c <>  -On -v 2c brocade-fcx .1.3.6.1.4.1.1991.1.1.1.1.2.0```

```
.1.3.6.1.4.1.1991.1.1.1.1.2.0 = STRING: "BCV2249F0P9"
```

**Comment by barryo** [comment]
@bcix - see comments in above commit.
