### ISSUE TITLE
Please add support for Brocade MLXe-16

### ISSUE THREAD

**Issue by kieber** [opensolutions/OSS_SNMP#21]
Hello Barry,

can you add support for Brocade MLXe-16 to OSS_SNMP so IXP-Manager can use it?

See output:

snmpget -c <> -On -v 2c 10.255.255.3 .1.3.6.1.2.1.1.1.0

.1.3.6.1.2.1.1.1.0 = STRING: "Brocade MLXe (System Mode: MLX), IronWare Version V5.7.0dT163 Compiled on Sep 23 2015 at 09:35:50 labeled as V5.7.00db"

snmpget -c <> -On -v 2c 10.255.255.3 .1.3.6.1.2.1.1.2.0

.1.3.6.1.2.1.1.2.0 = OID: .1.3.6.1.4.1.1991.1.3.55.1.2

snmpget -c <> -On -v 2c 10.255.255.3 .1.3.6.1.4.1.1991.1.1.1.1.2.0

.1.3.6.1.4.1.1991.1.1.1.1.2.0 = STRING: "BFQ4643L127"

**Comment by kieber** [comment]
Oh, and while you are at it, here is the output for Brocade Stackable ICX7450-48, that would be handy too:

snmpget -c <> -On -v 2c 10.255.255.17 .1.3.6.1.2.1.1.1.0

.1.3.6.1.2.1.1.1.0 = STRING: "Brocade Communications Systems, Inc. Stacking System ICX7450-48, IronWare Version 08.0.30dT213 Compiled on Nov  3 2015 at 22:16:04 labeled as SPR08030d"

snmpget -c <> -On -v 2c 10.255.255.17 .1.3.6.1.2.1.1.2.0

.1.3.6.1.2.1.1.2.0 = OID: .1.3.6.1.4.1.1991.1.3.48.8.3

snmpget -c <> -On -v 2c 10.255.255.17 .1.3.6.1.4.1.1991.1.1.1.1.2.0

.1.3.6.1.4.1.1991.1.1.1.1.2.0 = STRING: "CYQ2618K539"

**Comment by barryo** [comment]
Closed via #22 by @medea61
