### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by MHammett** [opensolutions/OSS_SNMP#37]
While working with some people on a Cisco mailing list, they pointed out that some of the links on:

https://github.com/opensolutions/OSS_SNMP/wiki/Device-Discovery

are broken.

**Comment by barryo** [comment]
Fixed:

https://github.com/opensolutions/OSS_SNMP/wiki/Device-Discovery/_compare/26a8dcfafbd59c9ce4cd12f01c7b26a9dbcbda04...f4cd8c750b0eafdd5afe765b4f9ad111fd08e412

Thanks,
Barry
