### ISSUE TITLE
how to get L3 interface IP

### ISSUE THREAD

**Issue by nchucc** [opensolutions/OSS_SNMP#42]
I can use snmpwalk get cisco L3 switch interfaces IP information
`snmpwalk -v 2c -c community  switchIP  1.3.6.1.2.1.4.20.1.1`
I search Document "\ OSS_SNMP \MIBS \Iface" not can find class
Is it possible to use in oss_snmp?

**Comment by kantholy** [comment]
use should be query all assigned IP addresses via `$host->useIP()->ipAddressList()`

see `OSS_SNMP/MIBS/Ip.php` - issue can be closed.

**Comment by barryo** [comment]
Thanks @kantholy
