### ISSUE TITLE
Php 7.1?

### ISSUE THREAD

**Issue by simPod** [opensolutions/OSS_SNMP#46]
Hello. I have just forked this library and plan to clean it up a bit, remove magic etc. because I want to use it. However I work only with php 7.1 and use all of it feature. That would cause BC break though. Would you be interested in such PR?

**Comment by barryo** [comment]
Hi @simPod - thanks for your interest but there are too many applications using this and (unfortunately) PHP 7.1 is too much of a requirement yet.
