### ISSUE TITLE
Parse error: syntax error, unexpected '[' in /src/OSS_SNMP/SNMP.php on line 543

### ISSUE THREAD

**Issue by jeneeben** [opensolutions/OSS_SNMP#47]
Hello,
for me the library is not working. As soon i include the SNMP.php i get following error:
Parse error: syntax error, unexpected '[' in /src/OSS_SNMP/SNMP.php on line 543

Regards,
Jeneeben

**Comment by barryo** [comment]
Hey @jeneeben - OSS_SNMP requires PHP >= v5.4. I suspect this is your issue.
