### ISSUE TITLE
Cisco Nexus 3064 version 7.0

### ISSUE THREAD

**Issue by MHammett** [opensolutions/OSS_SNMP#57]
root@Indy-IXPM:/home/mhammett# snmpget -c [redacted] -On -v 2c [redacted] .1.3.6.1.2.1.1.1.0
.1.3.6.1.2.1.1.1.0 = STRING: "Cisco NX-OS(tm) nxos.7.0.3.I6.2.bin, Software (nxos), Version 7.0(3)I6(2), RELEASE SOFTWARE Copyright (c) 2002-2016 by Cisco Systems, Inc. Compiled 10/17/2017 18:00:00"
root@Indy-IXPM:/home/mhammett# snmpget -c [redacted] -On -v 2c [redacted] .1.3.6.1.2.1.1.2.0
.1.3.6.1.2.1.1.2.0 = OID: .1.3.6.1.4.1.9.12.3.1.3.1105
root@Indy-IXPM:/home/mhammett# snmpget -c [redacted] -On -v 2c [redacted] .1.3.6.1.2.1.47.1.1.1.1.11.10
.1.3.6.1.2.1.47.1.1.1.1.11.10 = STRING: "FOC1637R0P3"

**Comment by barryo** [comment]
Not sure why this was opened - works without issue.
