### ISSUE TITLE
Add support for CE6870-24S6CQ-EI

### ISSUE THREAD

**Issue by vlalnt** [opensolutions/OSS_SNMP#63]
Need to add SNMP support for this switch in order to integrate new equipment.

Tried modifying `/srv/ixpmanager/vendor/opensolutions/oss-snmp/src/OSS_SNMP/Platforms/vendor_huawei.php` without success.

iso.3.6.1.2.1.1.1.0 = STRING: "Huawei Versatile Routing Platform Software
VRP (R) software, Version 8.150 (CE6870EI V200R002C50SPC800)
Copyright (C) 2012-2017 Huawei Technologies Co., Ltd.
HUAWEICE6870-24S6CQ-EI
"

.1.3.6.1.2.1.1.2.0 = OID: .1.3.6.1.4.1.2011.2.239.33

**Comment by Kergorn** [comment]
Unfortunatly, have the same problem with CE6870 :(
Hopefully this will be resolved soon
