### ISSUE TITLE
Support for v3 Contexts

### ISSUE THREAD

**Issue by timlegge** [opensolutions/OSS_SNMP#65]
Hi

I have bene looking at snmpsimd lately https://github.com/etingof/snmpsim and found that OSS_SNMP does not appear to support the snmp v3 concept of context.  Specifically it would need to use https://www.php.net/manual/en/snmp.setsecurity.php to set the context for the connection.  Any thought as to whether you might implement this?

Tim

**Comment by barryo** [comment]
Hey Tim,

I believe it works - [see this line](https://github.com/opensolutions/OSS_SNMP/blob/master/src/OSS_SNMP/SNMP.php#L204).

It wasn't done my me but via this PR: #15
