### ISSUE TITLE
Unable to discover the switch model through IXP Manager

### ISSUE THREAD

**Issue by udhay10881** [opensolutions/OSS_SNMP#71]
The IXP manager discovers the vendor but doesn't discover the model of the switch.

![image](https://user-images.githubusercontent.com/87021797/124607290-543c7200-de8b-11eb-906a-3fa4cdfdf887.png)

Also the switchports don't show up in IXP while mapping virtual interface to a physical interface

![image](https://user-images.githubusercontent.com/87021797/124607230-44bd2900-de8b-11eb-8d76-4878171dee53.png)

Switch details

NXOS: version 9.3(7)
Vendor Cisco
Model N9K-C93180YC-EX

**Comment by barryo** [comment]
Please provide the details requested in *Adding New Devices* on [this page](https://github.com/opensolutions/OSS_SNMP/wiki/Device-Discovery#adding-new-devices).

For the interface issue, please also post to a pastebin [such as this one](https://pastebin.ibn.ie/) the output of:

```
snmpget -c $community -On -v 2c $hostname .1.3.6.1.2.1.2.2
```

and

```
snmpget -c $community -On -v 2c $hostname .1.3.6.1.2.1.31
```
