### ISSUE TITLE
Support for Huawei  - S6720-54C-EI-48S-AC

### ISSUE THREAD

**Issue by aredan** [opensolutions/OSS_SNMP#72]
The SNMP query (snmpwalk) is returning:

.1.3.6.1.2.1.1.1.0 = STRING: "S6720-54C-EI-48S-AC
Huawei Versatile Routing Platform Software
 VRP (R) software,Version 5.170 (S6720 V200R010C00SPC600)
 Copyright (C) 2007 Huawei Technologies Co., Ltd."

We also edited a little bit the vendor_huawei.php file:

else if( preg_match('/^(S\d+\-[A-Z0-9\-]+)\s+Huawei Versatile Routing Platform Software\s+VRP \(R\) software,Version ([0-9\.]+) \((S[0-9]+) [A-Z0-9]+\)\s+Copyright \(C\) 2007 Huawei Technologies.*$/',

https://github.com/opensolutions/OSS_SNMP/pull/70/commits/df0c788d8df87d68241cf0e692b53712a8ad77dd

After that change the Switch is being detected, version and model are shown in the portal.

What we're seeing now is the lack of interface detection.

![image](https://user-images.githubusercontent.com/939894/131128979-4865f15c-e640-4031-8a65-81a055a8a329.png)

Looks like we need a vendor-specific Iface.php file with the OID for Huawei.

**Comment by barryo** [comment]
What does an snmp walk on .1.3.6.1.2.1.31 reveal?

Feel free to paste here: https://pastebin.ibn.ie/

**Comment by aredan** [comment]
This is the result:

![image](https://user-images.githubusercontent.com/939894/133347616-8e06f475-ac09-4876-862e-07f49f3a98c5.png)



I also uploaded the full snmpwalk to : https://pastebin.ibn.ie/?6a63942ac765143c#3Zt9vNtrdpzUwYAdXZifxPJYujxPc5BmokaE3m8LYAmB

**Comment by barryo** [comment]
Thanks @aredan - regex updated in master now. Can you check interface discovery with the most recent version of IXP Manager as there was a bug in recent versions around this.

**Comment by moviedo-sc** [comment]
The Switch is recognized by IXP Manager (V6.2.0), but it is not showing any port. Live port states show:
 
Could not update switch and switch port details via SNMP poll. Last successful poll: 2022-01-17 22:23:02.
 
The only logs I see are:
[2022-01-17 22:23:00] production.INFO:  [IXP-SW01] Platform: Found Model: S6720-54C-EI-48S-AC 
[2022-01-17 22:23:00] production.INFO:  [IXP-SW01] Platform: Found Os: Huawei Versatile Routing Platform Software VRP 
[2022-01-17 22:23:00] production.INFO:  [IXP-SW01] Platform: Updating OsDate from  to Unknown 
[2022-01-17 22:23:00] production.INFO:  [IXP-SW01] Platform: Found OsVersion: 5.170 
[2022-01-17 22:23:00] production.INFO:  [IXP-SW01] Platform: Found SerialNumber: (not implemented) 
[2022-01-17 22:23:06] production.INFO:  - IXP-SW01 - found pre-existing port for ifIndex 4 
[2022-01-17 22:23:06] production.INFO: [IXP-SW01]: [Index: 4] Updating Name from [] to [MEth0/0/1] 
 
Please let me know what other information could be useful to troubleshoot further.

**Comment by barryo** [comment]
What version of IXP Manager are you using @moviedo-sc ?

**Comment by moviedo-sc** [comment]
Running IXP Manager V6.2.0.
________________________________

**Comment by barryo** [comment]
What version of IXP Manager are you using @moviedo-sc ?

I can see it's finding the management port fine:

```
[2022-01-17 22:23:06] production.INFO:  - IXP-SW01 - found pre-existing port for ifIndex 4 
[2022-01-17 22:23:06] production.INFO: [IXP-SW01]: [Index: 4] Updating Name from [] to [MEth0/0/1] 
```

But the standard ports all look like they should be discovered without issue.

At this line, can you insert the following and paste the results to the pastebin?

```
dump( $host->useIface()->indexes() );
dump( $host->useIface()->names() );
dump( $host->useIface()->aliases() );
dump( $host->useIface()->descriptions() );
dump( $host->useIface()->speeds() );
dump( $host->useIface()->highSpeeds() );
dump( $host->useIface()->operationStates() );
dd( $host->useIface()->types() );
```
