### ISSUE TITLE
OSS-SNMP issue polling Port Channels on Dell OS9 and OS10

### ISSUE THREAD

**Issue by ninjaix** [opensolutions/OSS_SNMP#73]
We have an infrastructure using Dell (OS9 and OS10) VXLAN switches  (due so 'supply chain' issues).

LAG traffic is not showing up in IXPManager.  When I poll I see a space between Port-channel and the integer.

Dell OS9 Switch:
sysObjectID    .1.3.6.1.4.1.6027.1.5.2
Description    Dell EMC Networking OS..Operating System Version: 2.0..Application Software Version: 9.14(2.4)..Series: Z9100-ON..Copyright (c) 1999-2019 by Dell Inc. All Rights Reserved...Build Time: Fri Nov 8 09:08:12 2019

SNMP ifIndex       SNMP ifDescr       SNMP ifName       SNMP ifAlias       SNMP ifSpeed         
1258291712    Port-channel 1    Port-channel 1    Hurricane-LAG    10000000000

VS Arista EOS Switch:
1000002    Port-Channel2    Port-Channel2    Hurricane-Electric    200000000000

**Comment by barryo** [comment]
Hey @ninjaix - can you have a look at this issue on IXP Manager: https://github.com/inex/IXP-Manager/issues/513

That's possibly what's happening here?
