### ISSUE TITLE
Opengear CM7148-2-DAC

### ISSUE THREAD

**Issue by timlegge** [opensolutions/OSS_SNMP#76]
I am trying to query a serial console server for the port names and descriptions for the serial ports. The Iface.php is hard coded to use OID_IF_DESCRIPTION and OID_IF_NAME and this device only seems to send the Ethernet connections if Iface->descriptions or Iface->names is called.

Any idea how to query the serial interfaces that are in:

.1.3.6.1.4.1.25049.17.2.1.2.x or
.1.3.6.1.4.1.25049.16.1.1.11.x

**Comment by barryo** [comment]
Hi @timlegge - that's not a support function / device right now and would really require a new MIBS/Opengear/xxx file (or MIBS/xxx if generic). Happy to look at a PR if you want to submit one.
